openapi: 3.0.1
info:
  title: FHIR R4 Metadata API
  description: >
    This API provides the implementation of the FHIR capabilities interaction,
    enabling FHIR client applications to retrieve the server's capability statement.
    The capability statement details the server's current operational functionalities,
    including supported resource types and interactions.
  version: 1.0.0
servers:
  - url: https://api.example.com/fhir/r4
    description: FHIR R4 Production Server
paths:
  /metadata:
    get:
      operationId: getCapabilityStatement
      summary: Retrieve server capabilities
      description: >
        Returns a CapabilityStatement resource conforming to FHIR R4 specifications
        that describes the server's supported resources, interactions, search
        parameters, and operational capabilities.
      tags:
        - Metadata
      responses:
        '200':
          description: Returns FHIR international401:CapabilityStatement resource
          content:
            application/fhir+json:
              schema:
                type: object
        '400':
          description: Returns FHIR r4:OperationOutcome response
          content:
            application/fhir+json:
              schema:
                type: object
